// File generated by FlutterFire CLI.
// To regenerate, run `flutterfire configure`.
//
// IMPORTANT: Replace these placeholder values with your actual Firebase config.
// Run: dart run flutterfire_cli:flutterfire configure
// Or manually get values from Firebase Console > Project Settings.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Firebase Android config
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3yAHNst5ETXrn5WJVZzGvMbOSOivin_M',
    appId: '1:914342933376:android:9f48c66f422626c8cc8765',
    messagingSenderId: '914342933376',
    projectId: 'halo-e1d1a',
    storageBucket: 'halo-e1d1a.firebasestorage.app',
  );

  // TODO: Replace with your actual Firebase iOS config
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR-API-KEY',
    appId: 'YOUR-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId: 'YOUR-PROJECT-ID',
    storageBucket: 'YOUR-STORAGE-BUCKET',
    iosBundleId: 'com.halo.halo',
  );
}
