import 'package:cloud_firestore/cloud_firestore.dart';

/// Run this once from a debug button to seed 10 Sri Lankan test profiles.
/// Call: await SeedData.seedProfiles();
class SeedData {
  static final _db = FirebaseFirestore.instance;

  static Future<void> seedProfiles() async {
    final profiles = _buildProfiles();
    final batch = _db.batch();

    for (final profile in profiles) {
      final ref = _db.collection('users').doc(profile['uid'] as String);
      batch.set(ref, profile);
    }

    await batch.commit();
  }

  static List<Map<String, dynamic>> _buildProfiles() {
    final now = Timestamp.now();

    return [
      // ── Female profiles ────────────────────────────────────────────
      {
        'uid': 'test_user_001',
        'phoneNumber': '+94711000001',
        'name': 'Ayesha Perera',
        'dateOfBirth': Timestamp.fromDate(DateTime(1998, 3, 14)),
        'gender': 'female',
        'city': 'Colombo',
        'bio': 'Bookworm, coffee addict & hopeless romantic 📚☕',
        'photoUrls': ['https://randomuser.me/api/portraits/women/11.jpg'],
        'isPremium': false,
        'premiumUntil': null,
        'isVerified': true,
        'verificationStatus': 'approved',
        'isProfileComplete': true,
        'createdAt': now,
        'lastActive': now,
        'blockedUsers': [],
        'dailyLikesUsed': 0,
        'lastLikeResetDate': null,
        'personalityAnswers': {
          'Two truths and a lie...': 'I speak 3 languages, I hate curd rice, I\'ve climbed Sigiriya twice',
          'My most controversial opinion...': 'Kottu is overrated (please don\'t hate me)',
          'I\'m convinced that...': 'Pineapple on pizza is actually fine',
          'The most spontaneous thing I\'ve done...': 'Took a bus to Galle on a random Tuesday',
        },
        'lifestyleAnswers': {
          'My love language is...': 'Words of affirmation and long drives',
          'After work you\'ll find me...': 'At a café with a book or on a beach walk',
          'I\'m that person who...': 'Always has snacks in my bag',
          'On weekends I...': 'Visit temple in the morning, explore food spots after',
        },
        'relationshipAnswers': {
          'I\'m looking for...': 'Someone who can match my energy and my appetite',
          'My ideal date night...': 'Dinner at a rooftop in Colombo 7, then ice cream',
          'We\'ll get along if...': 'You enjoy deep conversations after midnight',
          'Together we could...': 'Travel every corner of Sri Lanka first',
        },
        'funAnswers': {
          'Dating me is like...': 'Discovering a hidden beach — worth the effort',
          'Let\'s debate this...': 'Is Kandy or Colombo the better city?',
        },
      },
      {
        'uid': 'test_user_002',
        'phoneNumber': '+94711000002',
        'name': 'Dilini Jayawardena',
        'dateOfBirth': Timestamp.fromDate(DateTime(1996, 7, 22)),
        'gender': 'female',
        'city': 'Kandy',
        'bio': 'Teacher by day, dancer by night 💃 Loves the hills',
        'photoUrls': ['https://randomuser.me/api/portraits/women/22.jpg'],
        'isPremium': true,
        'premiumUntil': Timestamp.fromDate(DateTime(2026, 6, 1)),
        'isVerified': true,
        'verificationStatus': 'approved',
        'isProfileComplete': true,
        'createdAt': now,
        'lastActive': now,
        'blockedUsers': [],
        'dailyLikesUsed': 0,
        'lastLikeResetDate': null,
        'personalityAnswers': {
          'Two truths and a lie...': 'I can cook 20 dishes, I hate Kandyan dance, I\'ve seen a leopard in the wild',
          'My most controversial opinion...': 'Kandy > Colombo, always',
          'I\'m convinced that...': 'Tea from Kandy hills cures everything',
          'The most spontaneous thing I\'ve done...': 'Hiked Knuckles Range alone at dawn',
        },
        'lifestyleAnswers': {
          'My love language is...': 'Acts of service — I\'ll cook for you',
          'After work you\'ll find me...': 'At dance rehearsal or the Kandy Lake',
          'I\'m that person who...': 'Wakes up at 5 am and loves it',
          'On weekends I...': 'Visit the Perahera or explore village markets',
        },
        'relationshipAnswers': {
          'I\'m looking for...': 'Someone grounded, kind and not afraid of family dinners',
          'My ideal date night...': 'Stargazing from a tea estate bungalow',
          'We\'ll get along if...': 'You appreciate culture and slow mornings',
          'Together we could...': 'Build something real, something lasting',
        },
        'funAnswers': {
          'Dating me is like...': 'A Kandyan drum — starts slow, then takes over everything',
          'Let\'s debate this...': 'Plain tea vs milk tea — which is superior?',
        },
      },
      {
        'uid': 'test_user_003',
        'phoneNumber': '+94711000003',
        'name': 'Nimesha Fernando',
        'dateOfBirth': Timestamp.fromDate(DateTime(2000, 11, 5)),
        'gender': 'female',
        'city': 'Galle',
        'bio': 'Graphic designer ✏️ Sea lover 🌊 Thrifter extraordinaire',
        'photoUrls': ['https://randomuser.me/api/portraits/women/33.jpg'],
        'isPremium': false,
        'premiumUntil': null,
        'isVerified': false,
        'verificationStatus': 'none',
        'isProfileComplete': true,
        'createdAt': now,
        'lastActive': now,
        'blockedUsers': [],
        'dailyLikesUsed': 2,
        'lastLikeResetDate': now,
        'personalityAnswers': {
          'Two truths and a lie...': 'I surf, I hate the beach heat, I own 3 cats',
          'My most controversial opinion...': 'The Fort is more beautiful than any mall in Colombo',
          'I\'m convinced that...': 'Galle fish ambul thiyal is the best dish in Sri Lanka',
          'The most spontaneous thing I\'ve done...': 'Quit my job and freelanced from Galle Fort for a month',
        },
        'lifestyleAnswers': {
          'My love language is...': 'Quality time — phone away, eyes on each other',
          'After work you\'ll find me...': 'Sketching at a fort café or at the beach',
          'I\'m that person who...': 'Re-decorates furniture instead of buying new',
          'On weekends I...': 'Explore antique shops or catch the sunset at Jungle Beach',
        },
        'relationshipAnswers': {
          'I\'m looking for...': 'Creative soul who appreciates slow living',
          'My ideal date night...': 'Sundowner at the Fort, then fresh seafood by the sea',
          'We\'ll get along if...': 'You don\'t rush through beautiful moments',
          'Together we could...': 'Open that little café we both probably dream about',
        },
        'funAnswers': {
          'Dating me is like...': 'Finding something vintage — unique and worth keeping',
          'Let\'s debate this...': 'Is the South better than the North for road trips?',
        },
      },
      {
        'uid': 'test_user_004',
        'phoneNumber': '+94711000004',
        'name': 'Savindi Wickramasinghe',
        'dateOfBirth': Timestamp.fromDate(DateTime(1994, 1, 30)),
        'gender': 'female',
        'city': 'Negombo',
        'bio': 'Nurse 👩‍⚕️ | Beach walks | Curd & treacle addict',
        'photoUrls': ['https://randomuser.me/api/portraits/women/44.jpg'],
        'isPremium': false,
        'premiumUntil': null,
        'isVerified': true,
        'verificationStatus': 'approved',
        'isProfileComplete': true,
        'createdAt': now,
        'lastActive': now,
        'blockedUsers': [],
        'dailyLikesUsed': 0,
        'lastLikeResetDate': null,
        'personalityAnswers': {
          'Two truths and a lie...': 'I\'ve delivered a baby, I hate hospitals, I can swim 2km',
          'My most controversial opinion...': 'Night shifts are actually peaceful',
          'I\'m convinced that...': 'The best conversations happen at 3am',
          'The most spontaneous thing I\'ve done...': 'Drove to Mannar to see the flamingos on a day off',
        },
        'lifestyleAnswers': {
          'My love language is...': 'Physical touch and small surprises',
          'After work you\'ll find me...': 'Walking the Negombo beach or napping (no judgment)',
          'I\'m that person who...': 'Checks on everyone but forgets to check on myself',
          'On weekends I...': 'Church, family lunch, then total freedom',
        },
        'relationshipAnswers': {
          'I\'m looking for...': 'Emotionally available, patient, and genuinely funny',
          'My ideal date night...': 'Prawn curry dinner, then a walk under the stars',
          'We\'ll get along if...': 'You don\'t mind that I fall asleep by 9pm sometimes',
          'Together we could...': 'Build a quiet, beautiful life by the sea',
        },
        'funAnswers': {
          'Dating me is like...': 'A warm lagoon — calm, clear and surprisingly deep',
          'Let\'s debate this...': 'Dutch Hospital or a local boutique for date night?',
        },
      },
      {
        'uid': 'test_user_005',
        'phoneNumber': '+94711000005',
        'name': 'Tharushi Silva',
        'dateOfBirth': Timestamp.fromDate(DateTime(1999, 6, 18)),
        'gender': 'female',
        'city': 'Batticaloa',
        'bio': 'Music teacher 🎸 East coast girl | String hoppers > everything',
        'photoUrls': ['https://randomuser.me/api/portraits/women/55.jpg'],
        'isPremium': false,
        'premiumUntil': null,
        'isVerified': false,
        'verificationStatus': 'none',
        'isProfileComplete': true,
        'createdAt': now,
        'lastActive': now,
        'blockedUsers': [],
        'dailyLikesUsed': 0,
        'lastLikeResetDate': null,
        'personalityAnswers': {
          'Two truths and a lie...': 'I play 4 instruments, I hate the lagoon, I\'ve performed at Colombo',
          'My most controversial opinion...': 'East coast beaches are way better than the south',
          'I\'m convinced that...': 'Music can fix any bad day',
          'The most spontaneous thing I\'ve done...': 'Joined a random wedding band for a night in Batti',
        },
        'lifestyleAnswers': {
          'My love language is...': 'Playing a song I wrote for someone special',
          'After work you\'ll find me...': 'By the lagoon with my guitar',
          'I\'m that person who...': 'Hums while cooking, always',
          'On weekends I...': 'Teach music to kids in the village, then beach time',
        },
        'relationshipAnswers': {
          'I\'m looking for...': 'Someone who has rhythm — in life, not just music',
          'My ideal date night...': 'Bonfire on Kallady beach with a guitar',
          'We\'ll get along if...': 'You can handle me randomly bursting into song',
          'Together we could...': 'Write the most beautiful story, one day at a time',
        },
        'funAnswers': {
          'Dating me is like...': 'A baila — you won\'t know the steps but you\'ll love it',
          'Let\'s debate this...': 'String hoppers or pittu — which wins breakfast?',
        },
      },

      // ── Male profiles ──────────────────────────────────────────────
      {
        'uid': 'test_user_006',
        'phoneNumber': '+94711000006',
        'name': 'Kasun Rathnayake',
        'dateOfBirth': Timestamp.fromDate(DateTime(1995, 4, 12)),
        'gender': 'male',
        'city': 'Colombo',
        'bio': 'Software engineer 💻 | Weekend hiker | Serious about coffee ☕',
        'photoUrls': ['https://randomuser.me/api/portraits/men/11.jpg'],
        'isPremium': false,
        'premiumUntil': null,
        'isVerified': true,
        'verificationStatus': 'approved',
        'isProfileComplete': true,
        'createdAt': now,
        'lastActive': now,
        'blockedUsers': [],
        'dailyLikesUsed': 0,
        'lastLikeResetDate': null,
        'personalityAnswers': {
          'Two truths and a lie...': 'I\'ve hiked Adam\'s Peak 3 times, I hate coding, I made it to finals in a hackathon',
          'My most controversial opinion...': 'TypeScript is better than JavaScript (change my mind)',
          'I\'m convinced that...': 'The best ideas come at 2am',
          'The most spontaneous thing I\'ve done...': 'Booked a flight to Bangkok with 6 hours notice',
        },
        'lifestyleAnswers': {
          'My love language is...': 'Quality time and acts of service',
          'After work you\'ll find me...': 'At the gym or debugging something I should\'ve fixed yesterday',
          'I\'m that person who...': 'Meal preps on Sunday and actually sticks to it',
          'On weekends I...': 'Hike or cycle in the morning, cook something new in the evening',
        },
        'relationshipAnswers': {
          'I\'m looking for...': 'Someone ambitious, warm and honest',
          'My ideal date night...': 'Rooftop dinner, then walking Colombo at night',
          'We\'ll get along if...': 'You appreciate silence as much as conversation',
          'Together we could...': 'Travel the world and still love coming home',
        },
        'funAnswers': {
          'Dating me is like...': 'A clean codebase — logical, reliable, no nasty surprises',
          'Let\'s debate this...': 'Is rice and curry really needed three times a day?',
        },
      },
      {
        'uid': 'test_user_007',
        'phoneNumber': '+94711000007',
        'name': 'Malith Gunawardena',
        'dateOfBirth': Timestamp.fromDate(DateTime(1993, 9, 8)),
        'gender': 'male',
        'city': 'Kandy',
        'bio': 'Doctor 👨‍⚕️ | Tea estate weekend escapes | Bookshelf goals',
        'photoUrls': ['https://randomuser.me/api/portraits/men/22.jpg'],
        'isPremium': true,
        'premiumUntil': Timestamp.fromDate(DateTime(2026, 5, 1)),
        'isVerified': true,
        'verificationStatus': 'approved',
        'isProfileComplete': true,
        'createdAt': now,
        'lastActive': now,
        'blockedUsers': [],
        'dailyLikesUsed': 0,
        'lastLikeResetDate': null,
        'personalityAnswers': {
          'Two truths and a lie...': 'I\'ve read 50 books this year, I love horror films, I grew up on a tea estate',
          'My most controversial opinion...': 'A long walk cures more than most medicines',
          'I\'m convinced that...': 'Kindness is the most attractive quality anyone can have',
          'The most spontaneous thing I\'ve done...': 'Spent a weekend at a monastery with zero phone signal',
        },
        'lifestyleAnswers': {
          'My love language is...': 'Words of affirmation and undivided attention',
          'After work you\'ll find me...': 'Reading or at the Kandy Lake for a quiet walk',
          'I\'m that person who...': 'Remembers your coffee order and your pet\'s name',
          'On weekends I...': 'Escape to a tea estate or go antiquing in Kandy',
        },
        'relationshipAnswers': {
          'I\'m looking for...': 'Depth over surface — someone I can grow with',
          'My ideal date night...': 'Candlelit dinner followed by the Perahera if the timing is right',
          'We\'ll get along if...': 'You believe in loyalty and laugh easily',
          'Together we could...': 'Create a home that always smells of tea and books',
        },
        'funAnswers': {
          'Dating me is like...': 'A well-steeped Ceylon tea — takes patience, completely worth it',
          'Let\'s debate this...': 'Should the national dish be kottu or rice and curry?',
        },
      },
      {
        'uid': 'test_user_008',
        'phoneNumber': '+94711000008',
        'name': 'Dineth Seneviratne',
        'dateOfBirth': Timestamp.fromDate(DateTime(1997, 2, 27)),
        'gender': 'male',
        'city': 'Gampaha',
        'bio': 'Entrepreneur 🚀 | Cricket on weekends | Mum\'s biryani > restaurant',
        'photoUrls': ['https://randomuser.me/api/portraits/men/33.jpg'],
        'isPremium': false,
        'premiumUntil': null,
        'isVerified': false,
        'verificationStatus': 'none',
        'isProfileComplete': true,
        'createdAt': now,
        'lastActive': now,
        'blockedUsers': [],
        'dailyLikesUsed': 3,
        'lastLikeResetDate': now,
        'personalityAnswers': {
          'Two truths and a lie...': 'I started a business at 22, I hate cricket, I\'ve been to India 5 times',
          'My most controversial opinion...': 'Home cooking will always beat any restaurant',
          'I\'m convinced that...': 'Every problem has a solution if you stay calm',
          'The most spontaneous thing I\'ve done...': 'Pitched to investors with a deck I made overnight',
        },
        'lifestyleAnswers': {
          'My love language is...': 'Acts of service — I\'ll fix it, plan it, sort it',
          'After work you\'ll find me...': 'On the phone with my team or watching cricket highlights',
          'I\'m that person who...': 'Always 10 minutes early and has a backup plan',
          'On weekends I...': 'Cricket with the boys, then big family lunch',
        },
        'relationshipAnswers': {
          'I\'m looking for...': 'Partner in life, not just romance — someone who gets the journey',
          'My ideal date night...': 'Cooking together at home, honest conversation, no screens',
          'We\'ll get along if...': 'You\'re ambitious but know how to switch off',
          'Together we could...': 'Build something the family will be proud of',
        },
        'funAnswers': {
          'Dating me is like...': 'A startup — uncertain at first, but high reward',
          'Let\'s debate this...': 'Is T20 cricket ruining test cricket or saving cricket altogether?',
        },
      },
      {
        'uid': 'test_user_009',
        'phoneNumber': '+94711000009',
        'name': 'Rusiru Bandara',
        'dateOfBirth': Timestamp.fromDate(DateTime(1996, 12, 3)),
        'gender': 'male',
        'city': 'Kurunegala',
        'bio': 'Farmer turned agri-tech founder 🌾 | Nature lover | Still learning',
        'photoUrls': ['https://randomuser.me/api/portraits/men/44.jpg'],
        'isPremium': false,
        'premiumUntil': null,
        'isVerified': false,
        'verificationStatus': 'pending',
        'isProfileComplete': true,
        'createdAt': now,
        'lastActive': now,
        'blockedUsers': [],
        'dailyLikesUsed': 0,
        'lastLikeResetDate': null,
        'personalityAnswers': {
          'Two truths and a lie...': 'I can identify 40 vegetables by smell, I hate the outdoors, I\'ve won an agri award',
          'My most controversial opinion...': 'We need to respect farmers more than influencers',
          'I\'m convinced that...': 'The future of Sri Lanka is in its villages, not its cities',
          'The most spontaneous thing I\'ve done...': 'Swapped my office job for a paddy field at 25',
        },
        'lifestyleAnswers': {
          'My love language is...': 'Presence — I put down my phone and really listen',
          'After work you\'ll find me...': 'Walking through the fields or reading about soil science',
          'I\'m that person who...': 'Can grow tomatoes but burns toast every single time',
          'On weekends I...': 'Farmers\' market, cook from scratch, sleep under stars if I can',
        },
        'relationshipAnswers': {
          'I\'m looking for...': 'Grounded person who knows what matters',
          'My ideal date night...': 'Cooking with garden vegetables, sitting outside after dark',
          'We\'ll get along if...': 'You don\'t need constant noise to feel comfortable',
          'Together we could...': 'Live simply, deeply and very happily',
        },
        'funAnswers': {
          'Dating me is like...': 'Tending a garden — slow but everything blooms beautifully',
          'Let\'s debate this...': 'Should we eat local always or is imported food sometimes okay?',
        },
      },
      {
        'uid': 'test_user_010',
        'phoneNumber': '+94711000010',
        'name': 'Ashan Thilakaratne',
        'dateOfBirth': Timestamp.fromDate(DateTime(1998, 8, 15)),
        'gender': 'male',
        'city': 'Matara',
        'bio': 'Marine biologist 🐠 | Surfer | Protector of our reefs',
        'photoUrls': ['https://randomuser.me/api/portraits/men/55.jpg'],
        'isPremium': false,
        'premiumUntil': null,
        'isVerified': true,
        'verificationStatus': 'approved',
        'isProfileComplete': true,
        'createdAt': now,
        'lastActive': now,
        'blockedUsers': [],
        'dailyLikesUsed': 0,
        'lastLikeResetDate': null,
        'personalityAnswers': {
          'Two truths and a lie...': 'I\'ve dived in the Maldives, I hate the ocean, I spotted a whale shark off Mirissa',
          'My most controversial opinion...': 'People who litter on beaches should clean them by hand',
          'I\'m convinced that...': 'The Indian Ocean is the most beautiful stretch of water on earth',
          'The most spontaneous thing I\'ve done...': 'Camped on a deserted beach for 4 days for field research',
        },
        'lifestyleAnswers': {
          'My love language is...': 'Shared adventures and genuine curiosity about the world',
          'After work you\'ll find me...': 'In the water or writing field reports by the sea',
          'I\'m that person who...': 'Always picks up plastic on the beach even off-duty',
          'On weekends I...': 'Surf, dive or take tourists on reef tours',
        },
        'relationshipAnswers': {
          'I\'m looking for...': 'Someone who loves this planet as much as I do',
          'My ideal date night...': 'Whale watching at dawn, then fresh catch dinner at sunset',
          'We\'ll get along if...': 'You\'re up for salt water, sandy feet and no WiFi sometimes',
          'Together we could...': 'Explore every reef in the Indian Ocean',
        },
        'funAnswers': {
          'Dating me is like...': 'Snorkelling — once you\'re in, you won\'t want to surface',
          'Let\'s debate this...': 'Mirissa or Arugam Bay — which has the better vibe?',
        },
      },
    ];
  }
}
